site_name:        Tick.jl
repo_url:         https://github.com/khigia/Tick.jl
site_description: Tick.jl computation graph
site_author:      Ludovic Coquelle

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Ideas: ideas.md
